
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import { AR_One_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = AR_One_Sans({ subsets: ["latin"], display: 'swap' });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.className}>
      <body>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
